### ISSUE TITLE
`SyntaxWarning` for invalid escape sequences in Python 3.12

### ISSUE THREAD

**Issue by Simon-Brandt** [ablab/spades#1457]
### Description of bug

In Python >= 3.6, invalid escape sequences for Unicode strings emit a `DeprecationWarning`, [changed](https://docs.python.org/release/3.12.0/whatsnew/changelog.html) to a `SyntaxWarning` in Python 3.12, to finally become a `SyntaxError` in a future Python version. SPAdes uses several of these invalid escape sequences across the Python scripts, most notably (or only?) in regular expressions. I obtained two of these warnings for a metaSPAdes run, in:

https://github.com/ablab/spades/blob/80f282ec864cd8f575c02d556c1f823c5b02e450/ext/src/python_libs/joblib3/func_inspect.py#L50-L52

and in:

https://github.com/ablab/spades/blob/80f282ec864cd8f575c02d556c1f823c5b02e450/ext/src/python_libs/joblib3/_memory_helpers.py#L10

To my knowledge, `<` and `>` should have never carried a specific meaning in Python's regex flavor and thus shouldn't have been required to escape, whilst the character classes `\s` and `\d` indeed do. As the `SyntaxWarning` will eventually become a `SyntaxError`, SPAdes will break, in the future. Since the same error has already been reported in #1320 and in #1326, but was only selectively fixed in 60ad35e, it may be preferable to go through the code base and find all strings with escape sequences and fix them, either by doubling the backslashes for Python's parser, or, preferred, by marking them as raw strings. If you want, I could try fixing this myself *via* pull request.

### spades.log

Since my dataset contains sensitive information (including the names of file paths), I cannot upload the `spades.log` and am only able to provide the following snippets. Since, however, the error should be clear, I hope more data isn't needed.

```yaml
Command line: /opt/spades/bin/spades.py --meta --threads=32 --memory=200 -1 /path/to/r1.fastq.gz -2 /path/to/r2.fastq.gz -o /path/to/metaspades_out_sample_1
                                                                                
System information:                                                             
  SPAdes version: 4.1.0                                                         
  Python version: 3.12.3                                                        
  OS: Linux-5.4.0-208-generic-x86_64-with-glibc2.39 
```

```python
== Running: /usr/bin/python3 /opt/spades/share/spades/spades_pipeline/scripts/compress_all.py --input_file /path/to/metaspades_out_sample_1/corrected/corrected.yaml --ext_python_modules_home /opt/spades/share/spades --max_threads 32 --output_dir /path/to/metaspades_out_sample_1/corrected --gzip_output
                                                                                
/opt/spades/share/spades/joblib3/func_inspect.py:51: SyntaxWarning: invalid escape sequence '\<'
  '\<doctest (.*\.rst)\[(.*)\]\>',                                              
/opt/spades/share/spades/joblib3/_memory_helpers.py:10: SyntaxWarning: invalid escape sequence '\s'
  cookie_re = re.compile("coding[:=]\s*([-\w.]+)")   
```

### params.txt

For the [`params.txt`](https://github.com/user-attachments/files/19362152/params.txt), I replaced the sensitive paths with `/path/to`.

### SPAdes version

SPAdes 4.1.0

### Operating System

Linux-5.4.0-208-generic-x86_64-with-glibc2.39

### Python Version

Python 3.12.3

### Method of SPAdes installation

Manual compilation, virtualized as Docker container, run as Singularity image

### No errors reported in spades.log

- [x] Yes
